version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: rai
      POSTGRES_PASSWORD: rai
      POSTGRES_DB: ros-database
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data/ros-database.sql:/ros-database.sql
      - ./restore.sh:/docker-entrypoint-initdb.d/restore.sh
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
